VoIP Kryptofon: ui.JSecState Class Reference
ui.JSecState Class Reference
Image indicating security state (unsecured/secured-unverified/secured-trusted).
Public Types
enum State { UNSECURED, VERIFIED, UNVERIFIED }
Possible security states.
Public Member Functions
JSecState (Object resourceOwner)
Constructs object in UNSECURED state by default.
State getState ()
Gets current security state.
void setState (State newState)
Stes new security state.
Private Attributes
State state
Current security state.
ImageIcon iconUnsecured
ImageIcon iconVerified
ImageIcon iconUnverified
Static Private Attributes
static final long serialVersionUID = 1853852857708971435L
Detailed Description
Image indicating security state (unsecured/secured-unverified/secured-trusted).
Author:
Mikica B Kocic
Definition at line 17 of file JSecState.java.
Member Enumeration Documentation
enum ui::JSecState::State
Possible security states.
Enumerator:
UNSECURED
Not secured (un-encrypted)
VERIFIED
Untrusted secured (remote party is not verified)
UNVERIFIED
Trusted secured (remote party is verified)
Definition at line 24 of file JSecState.java.
    {
        /** Not secured (un-encrypted) */
        UNSECURED,
        /** Untrusted secured (remote party is not verified) */
        VERIFIED,
        /** Trusted secured (remote party is verified) */
        UNVERIFIED
    };
Constructor & Destructor Documentation
ui.JSecState.JSecState (Object resourceOwner)
Constructs object in UNSECURED state by default.
Definition at line 50 of file JSecState.java.
References ui.JSecState.iconUnsecured, ui.JSecState.iconUnverified, ui.JSecState.iconVerified, ui.JImageButton.loadIcon(), and ui.JSecState.setState().
    {
        iconUnsecured  = JImageButton.loadIcon( resourceOwner, "unsecured.png" );
        iconVerified   = JImageButton.loadIcon( resourceOwner, "verified.png" );
        iconUnverified = JImageButton.loadIcon( resourceOwner, "unverified.png" );
        setState( State.UNSECURED );
        setMinimumSize( new Dimension( 32, 32 ) );
        setMaximumSize( new Dimension( 32, 32 ) );
    }
Member Function Documentation
State ui.JSecState.getState ()
Gets current security state.
Definition at line 64 of file JSecState.java.
References ui.JSecState.state.
    {
        return this.state;
    }
void ui.JSecState.setState (State newState)
Stes new security state.
Definition at line 72 of file JSecState.java.
References ui.JSecState.iconUnsecured, ui.JSecState.iconUnverified, ui.JSecState.iconVerified, and ui.JSecState.state.
Referenced by CryptoPhoneApp.acceptIncomingCall(), CryptoPhoneApp.deferredOnAccept(), CryptoPhoneApp.deferredOnBye(), CryptoPhoneApp.executeCommand(), ui.JSecState.JSecState(), and CryptoPhoneApp.tryToVerifyInvitingCall().
    {
        this.state = newState;
        switch( this.state )
        {
        case UNSECURED:
            setIcon( iconUnsecured );
            setToolTipText(
                    "<html><head></head><body><p><span style='color:red'>"
                    + "Unsecured and untrusted communication.</span>"
                    + "<br/>Instant messages will be unciphered and broadcasted to public."
                    + "</p></body></html>"
                    );
            break;
        case UNVERIFIED:
            setIcon( iconUnverified );
            setToolTipText(
                    "<html><head></head><body><p><span style='color:#8000FF'>"
                    + "Secured (encrypted) communication with unverified peer.</span>"
                    + "<br/>Instant messages will be ciphered and sent to peer only."
                    + "</p></body></html>"
                    );
            break;
        case VERIFIED:
            setIcon( iconVerified );
            setToolTipText(
                    "<html><head></head><body><p><span style='color:green'>"
                    + "Secured communication with the trusted peer.</span>"
                    + "<br/>Instant messages will be ciphered and sent to peer only."
                    + "</p></body></html>"
                    );
            break;
        }
    }
Member Data Documentation
ImageIcon ui.JSecState.iconUnsecured [private]
Definition at line 43 of file JSecState.java.
Referenced by ui.JSecState.JSecState(), and ui.JSecState.setState().
ImageIcon ui.JSecState.iconUnverified [private]
Definition at line 45 of file JSecState.java.
Referenced by ui.JSecState.JSecState(), and ui.JSecState.setState().
ImageIcon ui.JSecState.iconVerified [private]
Definition at line 44 of file JSecState.java.
Referenced by ui.JSecState.JSecState(), and ui.JSecState.setState().
final long ui.JSecState.serialVersionUID = 1853852857708971435L [static, private]
Definition at line 19 of file JSecState.java.
State ui.JSecState.state [private]
Current security state.
Definition at line 34 of file JSecState.java.
Referenced by ui.JSecState.getState(), and ui.JSecState.setState().
The documentation for this class was generated from the following file:
ui/JSecState.java