VoIP Kryptofon: pbx.PBXClient.Context Interface Reference
pbx.PBXClient.Context Interface Reference
Provides a call-back context for the instance of PBXClient.
Public Member Functions
abstract String getUserId ()
Returns configured user ID.
abstract void setPbxStatus (String str)
Updates PBX status message of the parent.
abstract void report (String style, String str)
Reports a system message to log.
void reportIncomingTextMessage (String cssClass, String userId, String message)
Reports incoming textual message.
abstract void onInvite (final ControlMessage cmsg)
Informs upper layer of incoming INVITE.
abstract void onRing (final ControlMessage cmsg)
Informs upper layer of incoming RING.
abstract void onAccept (final ControlMessage cmsg)
Informs upper layer of incoming ACCEPT.
abstract void onBye (final ControlMessage cmsg)
Informs upper layer of incoming BYE.
abstract void onInstantMessage (final ControlMessage cmsg)
Informs upper layer of incoming IMSG.
Detailed Description
Provides a call-back context for the instance of PBXClient.
Definition at line 100 of file PBXClient.java.
Member Function Documentation
abstract String pbx.PBXClient.Context.getUserId () [pure virtual]
Returns configured user ID.
Referenced by pbx.PBXClient.parseControlMessage(), pbx.PBXClient.sendAccept(), pbx.PBXClient.sendBye(), pbx.PBXClient.sendInstantMessage(), pbx.PBXClient.sendInvite(), pbx.PBXClient.sendListPeers(), and pbx.PBXClient.sendRing().
abstract void pbx.PBXClient.Context.onAccept (final ControlMessage cmsg) [pure virtual]
Informs upper layer of incoming ACCEPT.
Referenced by pbx.PBXClient.parseControlMessage().
abstract void pbx.PBXClient.Context.onBye (final ControlMessage cmsg) [pure virtual]
Informs upper layer of incoming BYE.
Referenced by pbx.PBXClient.parseControlMessage().
abstract void pbx.PBXClient.Context.onInstantMessage (final ControlMessage cmsg) [pure virtual]
Informs upper layer of incoming IMSG.
Referenced by pbx.PBXClient.parseControlMessage().
abstract void pbx.PBXClient.Context.onInvite (final ControlMessage cmsg) [pure virtual]
Informs upper layer of incoming INVITE.
Referenced by pbx.PBXClient.parseControlMessage().
abstract void pbx.PBXClient.Context.onRing (final ControlMessage cmsg) [pure virtual]
Informs upper layer of incoming RING.
Referenced by pbx.PBXClient.parseControlMessage().
abstract void pbx.PBXClient.Context.report (String style, String str) [pure virtual]
Reports a system message to log.
Referenced by pbx.PBXClient.report().
void pbx.PBXClient.Context.reportIncomingTextMessage (String cssClass, String userId, String message)
Reports incoming textual message.
Referenced by pbx.PBXClient.reportIncomingTextMessage().
abstract void pbx.PBXClient.Context.setPbxStatus (String str) [pure virtual]
Updates PBX status message of the parent.
Referenced by pbx.PBXClient.run().
The documentation for this interface was generated from the following file:
pbx/PBXClient.java